### PR TITLE
fix: variable format

### PR DESCRIPTION
**Pull request by kainlite**
fixes: https://github.com/vmfarms/client-elo-inc/issues/190

### CODE REVIEW

**Review by falpires — APPROVED** [review]

**Comment by falpires** [comment]
Approved, but i noted one thing. Where is the Chart.yaml being updated?

**Review by hany — APPROVED** [review]
LGTM with the exception of @falpires' comment

**Comment by kainlite** [comment]
> Approved, but i noted one thing. Where is the Chart.yaml being updated?

do you mean for the release version? I normally use:

```
helm package . --app-version=0.0.43 --version=0.0.43
```

but I can update the version there as well

**Comment by kainlite** [comment]
@falpires @hany do you mind checking again? I have just updated the `Chart.yaml` file

**Review by falpires — APPROVED** [review]

**Pull request merged**
